# Generated by Django 3.0.3 on 2020-03-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200309_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
