# Generated by Django 3.0.3 on 2020-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
